--- #---------------- CA OE1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ca-<orgName>
  name: ca-<orgName>
  namespace: <NameSpace>
spec:
  type: ClusterIP
  ports:
    - name: "https"
      port: 7054
      targetPort: 7054
  selector:
    app: ca-<orgName>
