---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-<chaincodeName>-<orgName>
  namespace: <NameSpace>
  labels:
    app: chaincode-<chaincodeName>-<orgName>
spec:
  selector:
    matchLabels:
      app: chaincode-<chaincodeName>-<orgName>
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-<chaincodeName>-<orgName>
    spec:
      containers:
        - image: <git>
          name: chaincode-<chaincodeName>-<orgName>
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_CCID
              value: "<CCID>"
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
