--- #---------------- Orderer0 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <ordererName>
  name: <ordererName>
  namespace: <NameSpace>
spec:
  type: ClusterIP
  ports:
    - name: "orderer"
      port: 7050
      targetPort: 7050
  selector:
    app: <ordererName>
---
#---------------- Orderer0 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <ordererName>
    metrics-service: "true"
  name: <ordererName>-metrics
  namespace: <NameSpace>
spec:
  type: ClusterIP
  ports:
    - name: "orderer-metrics"
      port: 8443
      targetPort: 8443
  selector:
    app: <ordererName>
