--- #---------------- Peer0 org1 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <peerName>
  name: <peerName>
  namespace: <NameSpace>
spec:
  selector:
    matchLabels:
      app: <peerName>
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: <peerName>
    spec:
      containers:
        - args:
            - peer
            - node
            - start
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_ADDRESS
              value: <peerName>:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: <peerName>:7051
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: <peerName>:7051
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: localhost:7052
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_ID
              value: <peerName>
            - name: CORE_PEER_LOCALMSPID
              value: <orgName>MSP
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_VM_ENDPOINT
              value: http://localhost:2375
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
            - name: CORE_METRICS_PROVIDER
              value: prometheus
          image: hyperledger/fabric-peer:amd64-2.1.0
          name: <peerFirstName>
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 9443
          volumeMounts:
            - mountPath: /host/var/run/
              name: <peerName>-claim0
            - mountPath: /etc/hyperledger/fabric/msp
              name: <peerName>-claim1
            - mountPath: /etc/hyperledger/fabric/tls
              name: <peerName>-claim2
            - mountPath: /var/hyperledger/production
              name: <peerFirstName>-persistentdata
            - mountPath: /etc/hyperledger/fabric/core.yaml
              name: builders-config
              subPath: core.yaml
            - mountPath: /builders/external
              name: external-builder
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
        - name: <peerName>-claim0
          hostPath:
            path: /var/run
            type: Directory
        - name: <peerName>-claim1
          hostPath:
            path: /mnt/nfsdata/fabric/<NameSpace>/crypto-config/peerOrganizations/<orgName>/peers/<peerName>/msp
            type: Directory
        - name: <peerName>-claim2
          hostPath:
            path: /mnt/nfsdata/fabric/<NameSpace>/crypto-config/peerOrganizations/<orgName>/peers/<peerName>/tls
            type: Directory
        - name: <peerFirstName>-persistentdata
          hostPath:
            path: /mnt/nfsdata/fabric/<NameSpace>/pau/old/storage/<peerName>
            type: DirectoryOrCreate
        - name: external-builder
          hostPath:
            path: /mnt/nfsdata/fabric/<NameSpace>/buildpack
        - name: builders-config
          configMap:
            name: builders-config
            items:
              - key: core.yaml
                path: core.yaml
